### ISSUE TITLE
Script in subfolders

### ISSUE THREAD

**Issue by marcpops** [cavo789/joomla_show_table#1]
Hi, thanks for your script: most useful!

I can't find a way to make it works when it's in subfolders.
I would like it in /administrator/showtable/showtable.php
"administrator" because it's already protected by a .htaccess/.htpasswd which is convenient.
"showtable" because I need to make several scripts and I want to collect them.

I've changed the root constant but it's not enough or I don't know how to do it properly.
Regards
Marc

**Comment by cavo789** [comment]
Hi Marc

Which error did you get ?

My script wasn't foreseen to be put elsewhere but nothing as you mentioned, the script can perfectly well be moved elsewhere and putting it in `/administrator` is a good idea, but you then have to update the paths in the source code.

For instance, the location of the `configuration.php` file (https://github.com/cavo789/joomla_show_table/blob/master/src/showtable.php#L406) has to be reviewed to go one folder up (the root of your site). As you can see on line 406, I refers to a constant called `ROOT` and you can find it on line 145 https://github.com/cavo789/joomla_show_table/blob/master/src/showtable.php#L145C25-L145C31.

So, instead of using `__DIR__`; can you just try putting your root folder like f.i. `/var/www/mysite`  (with or without the ending slash).

If I've coded things correctly years ago, just this single update should do the trick ;)

**Comment by marcpops** [comment]
Hi Christophe,
I've tried `public const ROOT = '/administrator/showtable/';` with and without the ending slash.
The script says: `The file /administrator/configuration.php can't be found, please review the ROOT constant to match your website root folder`

I've tried to put the script in administrator (not in 'showtable' subdirectory)  `public const ROOT = '/administrator/';` with and without the ending slash.
The script says: `The file /administrator/configuration.php can't be found, please review the ROOT constant to match your website root folder`

Any idea?

**Comment by cavo789** [comment]
The **full path** Marc; not the relative one.

And `ROOT` should be the root of your Joomla site so, something like `public const ROOT = '/var/www/mysite';`.

That path is where you'll find the `configuration.php` file of Joomla.

**Comment by marcpops** [comment]
Ok, got it.
My configuration.php is there:
`/home/testsite/public_html/configuration.php`
The script is there:
`/home/testsite/public_html/administrator/showtable/showtable-test.php`

So ROOT should be
`public const ROOT = '/home/testsite/public_html/';` (same with or without ending slash)
or
`public const ROOT = __DIR__ . '/../../';`

but the result is
```
Warning: include_once(/home/testsite/public_html/administrator/showtable/includes/defines.php) [function.include-once]: Failed to open stream: No such file or directory in /home/testsite/public_html/administrator/showtable/showtable-test.php on line 453

Warning: include_once() [function.include]: Failed opening '/home/testsite/public_html/administrator/showtable/includes/defines.php' for inclusion (include_path='.:/usr/share/php') in /home/testsite/public_html/administrator/showtable/showtable-test.php on line 453

Warning: include_once(/home/testsite/public_html/administrator/showtable/includes/framework.php) [function.include-once]: Failed to open stream: No such file or directory in /home/testsite/public_html/administrator/showtable/showtable-test.php on line 456

Warning: include_once() [function.include]: Failed opening '/home/testsite/public_html/administrator/showtable/includes/framework.php' for inclusion (include_path='.:/usr/share/php') in /home/testsite/public_html/administrator/showtable/showtable-test.php on line 456

Fatal error: Uncaught Error: Class "Joomla\CMS\Factory" not found in /home/testsite/public_html/administrator/showtable/showtable-test.php:459 Stack trace: #0 /home/testsite/public_html/administrator/showtable/showtable-test.php(190): ShowTable->loadConfiguration() #1 /home/testsite/public_html/administrator/showtable/showtable-test.php(512): ShowTable->__construct() #2 {main} thrown in /home/testsite/public_html/administrator/showtable/showtable-test.php on line 459
```

**Comment by marcpops** [comment]
But if I change
```
/* Initialize Joomla framework */
        define('_JEXEC', 1);
        // Load system defines
        if (file_exists(__DIR__ . '/../../' . '/defines.php')) {
            include_once __DIR__ . '/../../' . '/defines.php';
        }

        if (!defined('_JDEFINES')) {
            define('JPATH_BASE', __DIR__ . '/../../');
            include_once JPATH_BASE . '/includes/defines.php';
        }
```
it works fine.

**Comment by cavo789** [comment]
So, in your case, `public const ROOT = '/home/testsite/public_html';` should do the trick.

I've quickly checked my code (in fact the last changes done a few weeks ago) and my code isn't correct; so it's my fault.
I've patched the file (https://github.com/cavo789/joomla_show_table/commit/1733a8be78dcff541df04b4603e5b156ffc67f2a).

Can you get the last version and check again; sorry.

**Comment by cavo789** [comment]
> But if I change
> 
> ```
> /* Initialize Joomla framework */
>         define('_JEXEC', 1);
>         // Load system defines
>         if (file_exists(__DIR__ . '/../../' . '/defines.php')) {
>             include_once __DIR__ . '/../../' . '/defines.php';
>         }
> 
>         if (!defined('_JDEFINES')) {
>             define('JPATH_BASE', __DIR__ . '/../../');
>             include_once JPATH_BASE . '/includes/defines.php';
>         }
> ```
> 
> it works fine.

I was on it on the exact same time ;)

**Comment by marcpops** [comment]
Yes, thanks.
The updated script works fine now, with only the ROOT constant to adapt.
Thanks!

Since we're at it, it seems that line 262 is redundant?
`"		'fixedHeader': false,\n" .`

And a suggestion: since in your doc you give advice to copy/paste queries tested in Adminer/phpMyAdmin it is far more convenient to present your exemple query in Heredoc syntax.

Thanks again.
Marc

**Comment by cavo789** [comment]
Oh, I'll remove the line 262; nice.

For Heredoc, you're right but I personally don't like this syntax.  It's just a question of taste and colors ;)

With some editor, Heredoc will break your layout like the ability to fold all the code or some formatting tools don't like them.
But you're right, it's more convenient since just copy/paste.
